### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by le2Ks** [brimmen/phloxcoin#1]
Hello! Any addnodes to connect to the blockchain's network? Ty

**Comment by brimmen** [comment]
Yes m8. This was the first commit, and it's up and running now.  I'm working on windows cross compile, and blockexplorer

**Comment by le2Ks** [comment]
> 

Hello, no problem I will wait until the addnodes are announced then. Keep up the good work!

**Comment by le2Ks** [comment]
Btw If you need help on cross compile use MXE more info here https://mxe.cc/ 

 <img width="400"  src="https://i.imgur.com/uZf7tlG.png">

**Comment by brimmen** [comment]
> https://mxe.cc/
getconnectioncount=1
TY.vm. just what I needed, as this was a creation from lc0.8v, gitian-build is deprecated based on debian precise, and other dependencies, so was looking at MinGW-w64 or MXE (M cross-environment) for this purpose.

**Comment by le2Ks** [comment]
Sounds good glad I could help!

**Comment by le2Ks** [comment]
Please let us know the ip address of the node to connect once you're ready!

**Comment by le2Ks** [comment]
Tried to connect to 0xe00b8742, which equals to 224.11.135.66, but not working.

**Comment by brimmen** [comment]
try 0x42870be0

**Comment by le2Ks** [comment]
That worked thanks!

**Comment by le2Ks** [comment]
I will mine with just one single core, so the network difficulty remains at its slowest value.

**Comment by brimmen** [comment]
[Phloxcoin Block Explorer](http://66.135.29.251:3001/)

**Comment by brimmen** [comment]
> I will mine with just one single core, so the network difficulty remains at its slowest value.

[Phloxcoin Block Explorer](http://66.135.29.251:3001/)

**Comment by le2Ks** [comment]
Looking good!

**Comment by le2Ks** [comment]
Hello, did the blockchain restart? ty

EDIT: Nevermind it's just explorer a bit stuck, thought it was restarted. 

By the way is there a discord or telegram group for your project to chat on?  Can you make one?

**Comment by brimmen** [comment]
https://discord.gg/JPaYKBef

**Comment by brimmen** [comment]
> Btw If you need help on cross compile use MXE more info here https://mxe.cc/

I tried docker, mxe, but had success!! using gitian-builder.

![Screenshot from 2023-06-10 13-07-12](https://github.com/brimmen/phloxcoin/assets/24283345/82e29ee1-feda-4548-9654-b92306f6f59d)
